language: rust
before_script: 
- |
  cargo install --git https://github.com/rust-lang-nursery/rustfmt
  export PATH=$HOME/.cargo/bin:$PATH

script:
- |
  cargo-fmt -- --write-mode=diff &&
  cargo build &&
  cargo test

